name: Build vscode extension package
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - name: Build
        run: |
          npm install -g vsce @vercel/ncc
          npm ci
          npm run bundle && vsce package -o vscode-swissknife.vsix
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: preview_build.vsix
          path: preview_build.vsix
